---
# This playbook deploys WordPress on LEMP Stack on remote Servers

 - name: Configure WordPress on LEMP Stack 
   hosts: all
   become: yes

   roles:
     - ntp
     - db
     - nginx
     - php
     - wordpress
...
