---
# This playbook contains tasks to configure WordPress

- include_vars: ../../db/defaults/main.yml

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /usr/share/nginx/
    owner: root
    group: root
    mode: 0777
    copy: no

- name: Update NGINX's default site document root to point out to WordPress site
  lineinfile:
    name: /etc/nginx/conf.d/default.conf
    regexp: '(.)+root /var/www/html'
    line: 'root /usr/share/nginx/wordpress;'
  notify:
    - restart-nginx

- name: Update NGINX's default site document root to point out to WordPress site
  lineinfile:
    name: /etc/nginx/sites-available/default
    regexp: '(.)+root /var/www/html'
    line: 'root /usr/share/nginx/wordpress;'
  notify:
    - restart-nginx

- name: Update NGINX's default site document root to point out to WordPress site
  lineinfile:
    name: /etc/nginx/sites-enabled/default
    regexp: '(.)+root /var/www/html'
    line: 'root /usr/share/nginx/wordpress;'
  notify:
    - restart-nginx

- name: Copy the sample configuration file for WordPress
  command: mv /usr/share/nginx/wordpress/wp-config-sample.php /usr/share/nginx/wordpress/wp-config.php
  args:
    creates: /usr/share/nginx/wordpress/wp-config.php

- name: Update Wordpress configuration file
  lineinfile:
    name: /usr/share/nginx/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { 'regexp' : "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - { 'regexp' : "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - { 'regexp' : "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
    - { 'regexp' : "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', 'localhost');"}
...
