---
# This playbook contains a task to run docker container based on zainabalsaffar/ubuntu1604ansible:versionone

- name: install docker-py 
  command: pip3 install docker-py

- name: Run a container to test ansible playbook and roles
  docker_container:
    name: ansiblecontainer
    image: zainabalsaffar/ubuntu1604ansible:versionone
    state: present
    interactive: yes

