---
# tasks file for php

- name: Install PHP and dependencies
  apt:
    name: "{{ item  }}"
    state: present
  with_items:
    - php
    - php-fpm
    - php-mysql
    - php-mcrypt
    - php-gd

- name: configurethe php processor
  lineinfile:
    name: /etc/php/7.0/fpm/php.ini
    regexp: '(.)+cgi.fix_pathinfo=1'
    line: 'cgi.fix_pathinfo='
  notify:
    - restart-php7.0-fpm
...
